name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # her gün gece yarısı çalışır
  workflow_dispatch: {}
  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Generate snake animation SVG
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-grid-snake.svg?color_snake=#8E2DE2&color_dots=#f2e9f7,#dcbfe8,#c186d9,#a84dcb,#8E2DE2
            dist/github-contribution-grid-snake-dark.svg?color_snake=#FE428E&color_dots=#2a1330,#5c2a63,#9a3f8f,#d868a8,#FE428E

      - name: Push output to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
